---
ID: "ba59391f-25c7-42a8-938c-2e4c4dfd0662"
Parent: "7a5223a5-17fc-43e8-8b6c-9fb9f48763d7"
Template: "7a5223a5-17fc-43e8-8b6c-9fb9f48763d7"
Path: /sitecore/templates/Project/VisitUs/Base/_BasePage/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220217T110728Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
