---
ID: "c2efc276-52f9-4edc-886e-fee5bca906c7"
Parent: "730837d0-efb0-4ae5-b75c-c5623691007f"
Template: "730837d0-efb0-4ae5-b75c-c5623691007f"
Path: /sitecore/templates/Project/VisitUs/Pages/Listings/Trips/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{379496D6-6E69-4B30-8D40-7EF23ECEF2B4}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{204F9BD2-B023-4E9D-AF04-9113C8A2BD96}">
        <r
          id="{6B2336C3-B288-4753-A60E-BBD871F44600}"
          ph="altudo-main"
          uid="{7228FAE1-BDA8-423C-BC9C-DAF37F5DEF33}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220211T152006Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
